### ISSUE TITLE
access to release repo - trying to release for ROS2

### ISSUE THREAD

**Issue by flynneva** [bosch-ros-pkg-release/usb_cam-release#1]
I maintain the `ros2` branch for this package over at `ros-drivers/usb_cam` and want to prepare to make a release for it to ROS2. Is there any way anyone could grant me write access to this repo so I can push a new release?

**Comment by flynneva** [comment]
friendly ping @k-okada, or anyone else @wjwwood @SteveMacenski maybe?

**Comment by SteveMacenski** [comment]
I'm not a superadmin on this org, sorry I can't help. A good bet would be asking the maintainer of the ROS1 side to grant you access. Alternatively William or Tully can as well.

**Comment by wjwwood** [comment]
@flynneva I set up a team with access to this and invited you. So, once you accept you can do the release here.

There is this organization https://github.com/ros2-gbp but it doesn't really matter where the release repository is.

**Comment by flynneva** [comment]
> I set up a team with access to this and invited you. So, once you accept you can do the release here.

this is perfect! I actually was going to ask for access to the rviz animated view controller packages as well since I took those over too but this covers it.

**Comment by flynneva** [comment]
thank you so much!!!

**Comment by wjwwood** [comment]
Actually you'll need to be on another team too to get access to the view controller one, so I added you there too.
