### ISSUE TITLE
access to usb_cam-release for releasing in ros1

### ISSUE THREAD

**Issue by knorth55** [bosch-ros-pkg-release/usb_cam-release#2]
@wjwwood @tfoote
Hi, @twdragon and I (@knorth55 ) are now maintainers of `usb_cam`, but we don't have access to this repo.
can you give us write permission to this repo for the release?

**Comment by knorth55** [comment]
@wjwwood @tfoote kindly ping.
we are ready to release `usb_cam` for `noetic` and `melodic`.
but new maintainers have no write permission to this repo.

**Comment by tfoote** [comment]
@flynneva is a maintainer with access and has started responding: https://github.com/ros-drivers/usb_cam/pull/231#issuecomment-1455432057 I generally only interfere when current maintainers aren't available. I'm going to defer to him.

**Comment by knorth55** [comment]
@tfoote thanks!

@flynneva can you give us write permission to this repo for releasing usb_cam in ros1?

**Comment by knorth55** [comment]
@flynneva I made a PR as you said. https://github.com/ros2-gbp/ros2-gbp-github-org/pull/216
But I only get permission to 
https://github.com/ros2-gbp/usb_cam-release and didn't get permission to this repo...
It seems https://github.com/ros2-gbp/ros2-gbp-github-org/ only manage ros2 access permission.

@flynneva can you give me the permission of this repo?

**Comment by flynneva** [comment]
@knorth55 what are you trying to do? Access to that first usb_cam-release repo should be all you need to do a bloom release.

**Comment by knorth55** [comment]
@flynneva 
I want to release `usb_cam` in `ros1` `noetic` and `melodic`.
In order to do that, I need to have write permission to `ros-gbp/usb_cam-release` (this repo), not `ros2-gbp/usb_cam-release`.

can i do the `ros1` release in `ros2-gbp`?
I think  `ros2-gbp/usb_cam-release` is for `ros2` release, and this repo `ros-gbp/usb_cam-release` is for `ros1` release.
So I want to get the write permission to this repo `ros-gbp/usb_cam-release` not `ros2-gbp/usb_cam-release`.
It seems you did some `ros2` release in this repo, too, so I thought you have write permission to this repo.

as written in `ros/rosdistro`, `ros1` release repo (noetic and melodic) is `ros-gbp/usb_cam-release`.
https://github.com/ros/rosdistro/blob/f7a7098d872eab938035c2194059fa778f561e44/noetic/distribution.yaml#L11524-L11528

I misunderstood that https://github.com/ros2-gbp/ros2-gbp-github-org/ also manage the access to `ros1` release repo (like this repo).

**Comment by flynneva** [comment]
@knorth55 bloom won't care what repo you use. IMO I think you can use the ros2 release repo for the ros1 release if you want, you just have to update the track for bloom.

I don't think it matters 🤷‍♂️

**Comment by knorth55** [comment]
> I don't think it matters 

@flynneva 
IMO, there is no need to change release repo url.
`noetic` and `melodic` is already released in `ros-gbp/usb_cam-release`,
so I want to do the `noetic` and `melodic` release in this repo.
Also, in order to do release `noetic` and `melodic` in `ros2-gbp/usb_cam-release`, I need to change the repo url in `ros/rosdistro` first.
If you can give me the write permission of `ros-gbp/usb_cam-release` (this repo), I can do ROS1 release without the `ros/rosdistro` url change.
https://github.com/ros/rosdistro/blob/f7a7098d872eab938035c2194059fa778f561e44/noetic/distribution.yaml#L11524-L11528

So, can you give me write permission of this repo `ros-gbp/usb_cam-release`?
@tfoote told me to @flynneva can give the write permission of this repo.

**Comment by knorth55** [comment]
@flynneva Kindly ping.

Im sorry that I misunderstood the ros2 permission management, so the situation is messed up.
But the situation is quite simple.

What I want to do:
Release usb_cam in ROS1 melodic and Noetic

What I need:
Write permission of this repo `ros-gbp/usb_cam-release`

ROS1 `usb_cam` release repo url registred in rosdistro: 
`ros-gbp/usb_cam-release`

If I release ROS1 in `ros-gbp/usb_cam-release`, there is no need to change `ros/rosdistro` and I can just release with the write permission of this repo.

If I release ROS1 in `ros2-gbp/usb_cam-release`, I need to change the release url in`ros/rosdistro`.

I think it is reasonable to just give me the write permission of this repo, but what do you think?

**Comment by knorth55** [comment]
@flynneva 

This issue has stacked ros1 usb_cam release for almost three weeks.
I want to release ROS1 as soon as possible because of melodic last release.
I really need your help and consideration to ROS1, too.
I know you dont care about ROS1, but ROS1 is still active.

**Comment by tfoote** [comment]
@knorth55 Since @flynneva approved, I've invited you to the team with access list for this repo. Sorry the ros2-gbp access doesn't manage access here.

**Comment by knorth55** [comment]
@tfoote @flynneva Thank you!
